name: Deploy tested project to GCP

on:
  push:
    branches: [ master ]

jobs:
  call-build:
    uses: trevorism/actions-workflows/.github/workflows/build.yml@master

  call-deploy:
    uses: trevorism/actions-workflows/.github/workflows/deploy.yml@master
    if: success() || failure()
    needs: [call-build, call-accept-before]
    with:
      gcp_project: 'trevorism-action'
      gcp_project_id: '846837196321'
      version: '0-9-1'
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      TOKEN: ${{ secrets.TOKEN }}

  call-accept-before:
    uses: trevorism/actions-workflows/.github/workflows/accept.yml@master
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

  call-accept-after:
    uses: trevorism/actions-workflows/.github/workflows/accept.yml@master
    needs: call-deploy
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
